export const colors = {
  'black': 'var(--amino-black)',
  /* GRAY PALETTE */
  'gray-l80': 'var(--amino-gray-l80)',
  'gray-l60': 'var(--amino-gray-l60)',
  'gray-l40': 'var(--amino-gray-l40)',
  'gray-l20': 'var(--amino-gray-l20)',
  'gray-base': 'var(--amino-gray-base)',
  'gray-d20': 'var(--amino-gray-d20)',
  'gray-d40': 'var(--amino-gray-d40)',
  'gray-d60': 'var(--amino-gray-d60)',
  'gray-d80': 'var(--amino-gray-d80)',
  'gray-alpha': 'var(--amino-gray-alpha)',
  'gray-50': 'var(--amino-gray-50)',
  'gray-100': 'var(--amino-gray-100)',
  'gray-200': 'var(--amino-gray-200)',
  'gray-300': 'var(--amino-gray-300)',
  'gray-400': 'var(--amino-gray-400)',
  'gray-500': 'var(--amino-gray-500)',
  'gray-600': 'var(--amino-gray-600)',
  'gray-700': 'var(--amino-gray-700)',
  'gray-800': 'var(--amino-gray-800)',
  'gray-900': 'var(--amino-gray-900)',
  /* BLUE PALETTE */
  'blue-l80': 'var(--amino-blue-l80)',
  'blue-l60': 'var(--amino-blue-l60)',
  'blue-l40': 'var(--amino-blue-l40)',
  'blue-l20': 'var(--amino-blue-l20)',
  'blue-base': 'var(--amino-blue-base)',
  'blue-d20': 'var(--amino-blue-d20)',
  'blue-d40': 'var(--amino-blue-d40)',
  'blue-d60': 'var(--amino-blue-d60)',
  'blue-d80': 'var(--amino-blue-d80)',
  'blue-alpha': 'var(--amino-blue-alpha)',
  'blue-50': 'var(--amino-blue-50)',
  'blue-100': 'var(--amino-blue-100)',
  'blue-200': 'var(--amino-blue-200)',
  'blue-300': 'var(--amino-blue-300)',
  'blue-400': 'var(--amino-blue-400)',
  'blue-500': 'var(--amino-blue-500)',
  'blue-600': 'var(--amino-blue-600)',
  'blue-700': 'var(--amino-blue-700)',
  'blue-800': 'var(--amino-blue-800)',
  'blue-900': 'var(--amino-blue-900)',
  /* CYAN PALETTE */
  'cyan-l80': 'var(--amino-cyan-l80)',
  'cyan-l60': 'var(--amino-cyan-l60)',
  'cyan-l40': 'var(--amino-cyan-l40)',
  'cyan-l20': 'var(--amino-cyan-l20)',
  'cyan-base': 'var(--amino-cyan-base)',
  'cyan-d20': 'var(--amino-cyan-d20)',
  'cyan-d40': 'var(--amino-cyan-d40)',
  'cyan-d60': 'var(--amino-cyan-d60)',
  'cyan-d80': 'var(--amino-cyan-d80)',
  'cyan-alpha': 'var(--amino-cyan-alpha)',
  'cyan-50': 'var(--amino-cyan-50)',
  'cyan-100': 'var(--amino-cyan-100)',
  'cyan-200': 'var(--amino-cyan-200)',
  'cyan-300': 'var(--amino-cyan-300)',
  'cyan-400': 'var(--amino-cyan-400)',
  'cyan-500': 'var(--amino-cyan-500)',
  'cyan-600': 'var(--amino-cyan-600)',
  'cyan-700': 'var(--amino-cyan-700)',
  'cyan-800': 'var(--amino-cyan-800)',
  'cyan-900': 'var(--amino-cyan-900)',
  /* RED PALETTE */
  'red-l80': 'var(--amino-red-l80)',
  'red-l60': 'var(--amino-red-l60)',
  'red-l40': 'var(--amino-red-l40)',
  'red-l20': 'var(--amino-red-l20)',
  'red-base': 'var(--amino-red-base)',
  'red-d20': 'var(--amino-red-d20)',
  'red-d40': 'var(--amino-red-d40)',
  'red-d60': 'var(--amino-red-d60)',
  'red-d80': 'var(--amino-red-d80)',
  'red-alpha': 'var(--amino-red-alpha)',
  'red-50': 'var(--amino-red-50)',
  'red-100': 'var(--amino-red-100)',
  'red-200': 'var(--amino-red-200)',
  'red-300': 'var(--amino-red-300)',
  'red-400': 'var(--amino-red-400)',
  'red-500': 'var(--amino-red-500)',
  'red-600': 'var(--amino-red-600)',
  'red-700': 'var(--amino-red-700)',
  'red-800': 'var(--amino-red-800)',
  'red-900': 'var(--amino-red-900)',
  /* ORANGE PALETTE */
  'orange-l80': 'var(--amino-orange-l80)',
  'orange-l60': 'var(--amino-orange-l60)',
  'orange-l40': 'var(--amino-orange-l40)',
  'orange-l20': 'var(--amino-orange-l20)',
  'orange-base': 'var(--amino-orange-base)',
  'orange-d20': 'var(--amino-orange-d20)',
  'orange-d40': 'var(--amino-orange-d40)',
  'orange-d60': 'var(--amino-orange-d60)',
  'orange-d80': 'var(--amino-orange-d80)',
  'orange-alpha': 'var(--amino-orange-alpha)',
  'orange-50': 'var(--amino-orange-50)',
  'orange-100': 'var(--amino-orange-100)',
  'orange-200': 'var(--amino-orange-200)',
  'orange-300': 'var(--amino-orange-300)',
  'orange-400': 'var(--amino-orange-400)',
  'orange-500': 'var(--amino-orange-500)',
  'orange-600': 'var(--amino-orange-600)',
  'orange-700': 'var(--amino-orange-700)',
  'orange-800': 'var(--amino-orange-800)',
  'orange-900': 'var(--amino-orange-900)',
  /* GREEN PALETTE */
  'green-l80': 'var(--amino-green-l80)',
  'green-l60': 'var(--amino-green-l60)',
  'green-l40': 'var(--amino-green-l40)',
  'green-l20': 'var(--amino-green-l20)',
  'green-base': 'var(--amino-green-base)',
  'green-d20': 'var(--amino-green-d20)',
  'green-d40': 'var(--amino-green-d40)',
  'green-d60': 'var(--amino-green-d60)',
  'green-d80': 'var(--amino-green-d80)',
  'green-alpha': 'var(--amino-green-alpha)',
  'green-50': 'var(--amino-green-50)',
  'green-100': 'var(--amino-green-100)',
  'green-200': 'var(--amino-green-200)',
  'green-300': 'var(--amino-green-300)',
  'green-400': 'var(--amino-green-400)',
  'green-500': 'var(--amino-green-500)',
  'green-600': 'var(--amino-green-600)',
  'green-700': 'var(--amino-green-700)',
  'green-800': 'var(--amino-green-800)',
  'green-900': 'var(--amino-green-900)',
  /* PURPLE */
  'purple-l80': 'var(--amino-purple-l80)',
  'purple-l60': 'var(--amino-purple-l60)',
  'purple-l40': 'var(--amino-purple-l40)',
  'purple-l20': 'var(--amino-purple-l20)',
  'purple-base': 'var(--amino-purple-base)',
  'purple-d20': 'var(--amino-purple-d20)',
  'purple-d40': 'var(--amino-purple-d40)',
  'purple-d60': 'var(--amino-purple-d60)',
  'purple-d80': 'var(--amino-purple-d80)',
  'purple-alpha': 'var(--amino-purple-alpha)',
  'purple-50': 'var(--amino-purple-50)',
  'purple-100': 'var(--amino-purple-100)',
  'purple-200': 'var(--amino-purple-200)',
  'purple-300': 'var(--amino-purple-300)',
  'purple-400': 'var(--amino-purple-400)',
  'purple-500': 'var(--amino-purple-500)',
  'purple-600': 'var(--amino-purple-600)',
  'purple-700': 'var(--amino-purple-700)',
  'purple-800': 'var(--amino-purple-800)',
  'purple-900': 'var(--amino-purple-900)',
  /* YELLOW PALLETE */
  'yellow-l80': 'var(--amino-yellow-l80)',
  'yellow-l60': 'var(--amino-yellow-l60)',
  'yellow-l40': 'var(--amino-yellow-l40)',
  'yellow-l20': 'var(--amino-yellow-l20)',
  'yellow-base': 'var(--amino-yellow-base)',
  'yellow-d20': 'var(--amino-yellow-d20)',
  'yellow-d40': 'var(--amino-yellow-d40)',
  'yellow-d60': 'var(--amino-yellow-d60)',
  'yellow-d80': 'var(--amino-yellow-d80)',
  'yellow-alpha': 'var(--amino-yellow-alpha)',
  'yellow-50': 'var(--amino-yellow-50)',
  'yellow-100': 'var(--amino-yellow-100)',
  'yellow-200': 'var(--amino-yellow-200)',
  'yellow-300': 'var(--amino-yellow-300)',
  'yellow-400': 'var(--amino-yellow-400)',
  'yellow-500': 'var(--amino-yellow-500)',
  'yellow-600': 'var(--amino-yellow-600)',
  'yellow-700': 'var(--amino-yellow-700)',
  'yellow-800': 'var(--amino-yellow-800)',
  'yellow-900': 'var(--amino-yellow-900)',
  'amber-alpha': 'var(--amino-amber-alpha)',
  'amber-50': 'var(--amino-amber-50)',
  'amber-100': 'var(--amino-amber-100)',
  'amber-200': 'var(--amino-amber-200)',
  'amber-300': 'var(--amino-amber-300)',
  'amber-400': 'var(--amino-amber-400)',
  'amber-500': 'var(--amino-amber-500)',
  'amber-600': 'var(--amino-amber-600)',
  'amber-700': 'var(--amino-amber-700)',
  'amber-800': 'var(--amino-amber-800)',
  'amber-900': 'var(--amino-amber-900)',
} as const;

export const commonColors = {
  'danger': 'var(--amino-danger)',
  'danger-dark': 'var(--amino-danger-dark)',
  'error': 'var(--amino-error)',
  'primary': 'var(--amino-primary)',
  'primary-light': 'var(--amino-primary-light)',
  'primary-dark': 'var(--amino-primary-dark)',
  'success': 'var(--amino-success)',
  'success-dark': 'var(--amino-success-dark)',
  'warning': 'var(--amino-warning)',
  'warning-dark': 'var(--amino-warning-dark)',
} as const;

export const glowColors = {
  'glow-error': 'var(--amino-glow-error)',
  'glow-blue': 'var(--amino-glow-blue)',
  'glow-cyan': 'var(--amino-glow-cyan)',
  'glow-red': 'var(--amino-glow-red)',
  'glow-orange': 'var(--amino-glow-orange)',
  'glow-green': 'var(--amino-glow-green)',
  'glow-purple': 'var(--amino-glow-purple)',
} as const;

export const layoutColors = {
  'page-background': 'var(--amino-page-background)',
  'border-color': 'var(--amino-border-color)',
  'hover-color': 'var(--amino-hover-color)',
  'surface-color': 'var(--amino-surface-color)',
  'surface-color-secondary': 'var(--amino-surface-color-secondary)',
  'text-light': 'var(--amino-text-light)',
  'text-color': 'var(--amino-text-color)',
  'text-dark': 'var(--amino-text-dark)',
  'input-background': 'var(--amino-input-background)',
} as const;

export const colorStyleList = {
  ...colors,
  ...commonColors,
  ...glowColors,
  ...layoutColors,
};
