export declare const aminoErrorToast: string;
export declare const aminoInfoToast: string;
export declare const aminoSuccessToast: string;
export declare const aminoToast: string;
export declare const aminoWarningToast: string;
export declare const dismissButton: string;
export declare const persistentToast: string;
export declare const toastContent: string;
export declare const toastIcon: string;
