export enum AminoTheme {
  transition = "--amino-transition",

  typeScaleBase = "--amino-type-scale-base",

  type4Xl = "--amino-text-xxxxl",
  type3Xl = "--amino-text-xxxl",
  type2Xl = "--amino-text-xxl",
  typeXl = "--amino-text-xl",
  textLg = "--amino-text-lg",
  textMd = "--amino-text-md",
  textBase = "--amino-text-base",
  textSm = "--amino-text-sm",
  textXs = "--amino-text-xs",

  space = "--amino-space",
  spaceNegative = "--amino-space-negative",
  spaceHalf = "--amino-space-half",
  spaceHalfNegative = "--amino-space-half-negative",
  spaceQuarter = "--amino-space-quarter",
  spaceQuarterNegative = "--amino-space-quarter-negative",
  spaceDouble = "--amino-space-double",
  spaceDoubleNegative = "--amino-space-double-negative",

  radiusSm = "--amino-radius-sm",
  radius = "--amino-radius",
  radiusLg = "--amino-radius-lg",

  gray50 = '--amino-gray-50',
  gray100 = '--amino-gray-100',
  gray200 = '--amino-gray-200',
  gray300 = "--amino-gray-300",
  gray400 = "--amino-gray-400",
  gray500 = '--amino-gray-500',
  gray600 = '--amino-gray-600',
  gray700 = "--amino-gray-700",
  gray900 = "--amino-gray-900",

  blue50 = '--amino-blue-50',
  blue100 = '--amino-blue-100',
  blue200 = '--amino-blue-200',
  blue300 = "--amino-blue-300",
  blue400 = "--amino-blue-400",
  blue500 = '--amino-blue-500',
  blue600 = '--amino-blue-600',
  blue700 = "--amino-blue-700",
  blue900 = "--amino-blue-900",
  blueAlpha = "--amino-blue-alpha",

  cyanAlpha = "--amino-cyan-alpha",
  cyan300 = "--amino-cyan-300",
  cyan400 = "--amino-cyan-400",
  cyan700 = "--amino-cyan-700",
  cyan900 = "--amino-cyan-900",

  redAlpha = "--amino-red-alpha",
  red300 = "--amino-red-300",
  red400 = "--amino-red-400",
  red700 = "--amino-red-700",
  red900 = "--amino-red-900",

  orangeAlpha = "--amino-orange-alpha",
  orange300 = "--amino-orange-300",
  orange400 = "--amino-orange-400",
  orange700 = "--amino-orange-700",
  orange900 = "--amino-orange-900",

  greenAlpha = "--amino-green-alpha",
  green300 = "--amino-green-300",
  green400 = "--amino-green-400",
  green700 = "--amino-green-700",
  green900 = "--amino-green-900",

  glowBlue = "--amino-glow-blue",
  glowCyan = "--amino-glow-cyan",
  glowRed = "--amino-glow-red",
  glowOrange = "--amino-glow-orange",
  greenOrange = "--amino-green-orange",

  primary = "--amino-primary",
  primaryLight = "--amino-primary-light",
  primaryDark = "--amino-primary-dark",

  success = "--amino-success",
  warning = "--amino-warning",
  error = "--amino-error",

  pageBackground = "--amino-page-background",
  borderColor = "--amino-border-color",
  hoverColor = "--amino-hover-color",
  surfaceColor = "--amino-surface-color",
  surfaceColorSecondary = "--amino-surface-color-secondary",

  textLight = "--amino-text-light",
  textColor = "--amino-text-color",
  textDark = "--amino-text-dark",

  inputBackground = "--amino-input-background",
  containerWidth = "--amino-container-width",
  appbarHeight = "--amino-appbar-height",
  sidebarWidth = "--amino-sidebar-width",
  sidebarColor = "--amino-sidebar-color",

  fontSans = "--amino-font-sans",
  fontMono = "--amino-font-mono",

  shadowInset = "--amino-shadow-inset",
  shadowSmall = "--amino-shadow-small",
  shadowBase = "--amino-shadow-base",
  shadowMedium = "--amino-shadow-medium",
  shadowLarge = "--amino-shadow-large",
  shadowLarger = "--amino-shadow-larger",

  border = "--amino-border",
  borderBlue = "--amino-border-blue",
  borderRed = "--amino-border-red",
  borderCyan = "--amino-border-cyan",
  borderOrange = "--amino-border-orange",
  borderGreen = "--amino-border-green",
  borderTransparent = "--amino-border-transparent"
}
