export declare const bordered: string;
export declare const collapsible: string;
export declare const loading: string;
export declare const noHeaders: string;
export declare const noPadding: string;
export declare const skeletonCellWrapper: string;
export declare const styledCheckbox: string;
export declare const tableContainer: string;
export declare const tableStyled: string;
