export declare const badgeWrapper: string;
export declare const controlsWrapper: string;
export declare const disabled: string;
export declare const dropdownWrapper: string;
export declare const filterText: string;
export declare const filterTitle: string;
export declare const filterWrapper: string;
export declare const styledDropdownTrigger: string;
export declare const toggleWrapper: string;
