export declare const aminoCheckbox: string;
export declare const checkboxContainer: string;
export declare const checked: string;
export declare const disabled: string;
export declare const infoWrapper: string;
export declare const labelWrapper: string;
export declare const styledLabel: string;
export declare const styledLabelDescription: string;
export declare const styledSubtitle: string;
